# --- Redis deployment ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7
          resources:
            limits:
              memory: "4096Mi"
              cpu: "750m"
            requests:
              memory: "4096Mi"
              cpu: "750m"
          ports:
            - containerPort: 6379
---
# --- Redis service ---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  ports:
    - port: 6379          # Service port
      targetPort: 6379    # Container port
---
# --- RabbitMQ deployment ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:latest
          resources:
            limits:
              memory: "4096Mi"
              cpu: "750m"
            requests:
              memory: "4096Mi"
              cpu: "750m"
          ports:
            - containerPort: 5672
---
# --- RabbitMQ service ---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
    - port: 5672          # Service port
      targetPort: 5672    # Container port
---
# --- Flask app deployment --
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apptest
spec:
  replicas: 5
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: tkolstee/sample-flask-app:latest
          tty: true
          resources:
            limits:
              memory: "4096Mi"
              cpu: "750m"
            requests:
              memory: "4096Mi"
              cpu: "750m"
          ports:
            - containerPort: 8000
          env:
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  type: NodePort
  selector:
    app: flask-app
  ports:
    - port: 8000          # Service port
      targetPort: 8000    # Container port
      nodePort: 30080     # Node port (must be between 30000-32767)
---
# --- Rabbit consumer app deployment --
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbit-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbit-consumer
  template:
    metadata:
      labels:
        app: rabbit-consumer
    spec:
      containers:
        - name: rabbit-consumer
          image: tkolstee/sample-rabbit-consumer:latest
          tty: true
          resources:
            limits:
              memory: "4096Mi"
              cpu: "750m"
            requests:
              memory: "4096Mi"
              cpu: "750m"
          env:
            - name: MQ_SERVER
              value: "rabbitmq"
            - name: MQ_USER
              value: "guest"
            - name: MQ_PASS
              value: "guest"
      imagePullSecrets:
        - name: regcred
---
# --- Rabbit producer app deployment --
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbit-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbit-producer
  template:
    metadata:
      labels:
        app: rabbit-producer
    spec:
      containers:
        - name: rabbit-producer
          image: tkolstee/sample-rabbit-producer:latest
          tty: true
          resources:
            limits:
              memory: "4096Mi"
              cpu: "750m"
            requests:
              memory: "4096Mi"
              cpu: "750m"
          env:
            - name: MQ_SERVER
              value: "rabbitmq"
            - name: MQ_USER
              value: "guest"
            - name: MQ_PASS
              value: "guest"
      imagePullSecrets:
        - name: regcred