# --- Redis deployment ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7
          ports:
            - containerPort: 6379
# --- Redis service ---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  ports:
    - port: 6379          # Service port
      targetPort: 6379    # Container port
  clusterIP: None
---
# --- Flask app deployment --
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apptest
spec:
  replicas: 5
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: tkolstee/sample-flask-app:latest
          ports:
            - containerPort: 8000
          env:
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
        - name: redis
          image: redis:7
          ports:
            - containerPort: 6379
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  type: NodePort
  selector:
    app: flask-app
  ports:
    - port: 8000          # Service port
      targetPort: 8000    # Container port
      nodePort: 30080     # Node port (must be between 30000-32767)
