---   # Flask app deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apptest
spec:
  replicas: 5
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: docker.io/tkolstee/sample-flask-app
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
          tty: true
          ports:
            - containerPort: 8000
          env:
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
---  # Flask app service
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  type: NodePort
  selector:
    app: flask-app
  ports:
    - port: 8000          # Service port
      targetPort: 8000    # Container port
      nodePort: 30080     # Node port (must be between 30000-32767)
