---   # RabbitMQ producer app deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbit-producer
spec:
  replicas: 5
  selector:
    matchLabels:
      app: rabbit-producer
  template:
    metadata:
      labels:
        app: rabbit-producer
    spec:
      containers:
        - name: rabbit-producer
          image: docker.io/tkolstee/sample-rabbit-producer
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          tty: true
          env:
            - name: MQ_SERVER
              value: "rabbitmq"
            - name: MQ_USER
              value: "guest"
            - name: MQ_PASS
              value: "guest"
